name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  OPENAI_API_KEY: test-api-key
  RAG_API_KEYS: dev-astro-key
  PYTHONPATH: backend

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-asyncio

      - name: Run tests
        working-directory: backend
        run: pytest tests

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: astroloji/backend:ci-${{ github.sha }}

  canary-deploy:
    name: Canary Deploy (dry-run)
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dry-run canary deployment
        run: bash scripts/deploy_canary.sh

  rollback-on-failure:
    name: Canary Rollback
    if: failure()
    runs-on: ubuntu-latest
    needs: [lint-test, docker-build, canary-deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute rollback script
        run: bash scripts/rollback_canary.sh

